### ISSUE TITLE
ZF2 DhErrorLogging\\Options\\Factory\\ModuleOptionsFactory::__invoke() 

### ISSUE THREAD

**Issue by pacificnm** [DavidHavl/DhErrorLogging#20]
Not sure why this is happening but here is the error. 
Argument 1 passed to DhErrorLogging\\Options\\Factory\\ModuleOptionsFactory::__invoke() must be an instance of Interop\\Container\\ContainerInterface, instance of Zend\\ServiceManager\\ServiceManager given.

Changing: 
public function __invoke(ContainerInterface $container, $name, array $options = null)
to: 
public function __invoke(ServiceLocatorInterface $container, $name, array $options = null) resolves the issue. 

running ZF 2.4

**Comment by vrkansagara** [comment]
Same issue with `2.4.13`

**Comment by DavidHavl** [comment]
Are you having mix of ZF 2.4 and 3.0 components?
ZF 2 uses createService method for factories and sends ServiceLocatorInterface, whereas ZF 3 uses _invoke for factories and sends ContainerInterface. 
You are describing mix of those 2 which is strange.
Anyway, one way to fix it is to create your own version of the file DhErrorLogging\Options\Factory\ModuleOptionsFactory.php (with the change you wrote) an set it to 'DhErrorLogging\Options\ModuleOptions' entry in your service manager config. So something like that
`'service_manager' => [
        'factories' => [
            'DhErrorLogging\Options\ModuleOptions' => 'DhErrorLogging\Options\Factory\ModuleOptionsFactory',
............. ] ]
`

**Comment by vrkansagara** [comment]
@DavidHavl  The issue is not resolved and I believe the issue should be reopened.
I am facing this issue with `"zendframework/zendframework": "~2.4.11",`

**Comment by pacificnm** [comment]
The project I was working on was using only 2.4.11 no 3.0 at all. The resolution I provided worked and has been in production for 7 months.

**Comment by vrkansagara** [comment]
@pacificnm  can you share me your `composer.json ` file.

**Comment by vrkansagara** [comment]
@pacificnm If I following your suggestion it takes me to each and every factory class to change the same. It's really bad.

**Comment by pacificnm** [comment]
@vrkansagara I only edited one file DhErrorLogging\Options\Factory\ModuleOptionsFactory::__invoke()

**Comment by vrkansagara** [comment]
@pacificnm  I am using `"minimum-stability": "dev",`  . It might causing

**Comment by pacificnm** [comment]
```

	"minimum-stability" : "dev",
	"require" : {
		"php" : ">=5.5.0",
		"zendframework/zendframework" : "2.4.0",
		"ezyang/htmlpurifier" : "^4.8",
		"paypal/rest-api-sdk-php" : "*",
		"google/cloud" : "^0.21.1",
		"ewgo/solarium-module" : "1.0.2",
		"davidhavl/dherrorlogging" : "~2.0",
         }   
```

**Comment by vrkansagara** [comment]
@pacificnm  still not working.

**Comment by pacificnm** [comment]
Whats the error?

Looking back at that project I actually abandon using DhErrorLogging and wrote my own logging based on the work from this project so I no longer have a working example.

**Comment by DavidHavl** [comment]
Found the issue. The old ServiceManager does not implement ContainerInterface in version 2.4 yet, only in later versions. The fix is to either update your Zend\ServiceManager\ServiceManager to the next minor version (2.7), or rewrite the createService (not the _invoke) method of each factory of this module. But will that work for you anyway? The current version of this module (2.2.1) requires zend components v2.6 and up anyway.

**Comment by pacificnm** [comment]
I always figured it was an issue with the version of ZF

**Comment by DavidHavl** [comment]
@pacificnm yes the v2.4 was problematic.

Here is 2.4:

`
    namespace Zend\ServiceManager;

    class ServiceManager implements ServiceLocatorInterface
    {
`

And here is the next version in line (2.7):

`
    namespace Zend\ServiceManager;

    use Interop\Container\ContainerInterface;

    class ServiceManager implements ServiceLocatorInterface, ContainerInterface
    {
`

Basically they just added an additional interface so it is compatible with 3.0 but changed signature of factories.

**Comment by vrkansagara** [comment]
@pacificnm  and @DavidHavl  I am new to the `ZF` project so can you guide me what changes I have to do with `2.4` version.

**Comment by DavidHavl** [comment]
A super easy fix would be to add an additional Interface (Interop\Container\ContainerInterface) to the Zend ServiceManager
so it would look like this:

```
use Interop\Container\ContainerInterface;

class ServiceManager implements ServiceLocatorInterface, ContainerInterface
{
....
```

**Comment by vrkansagara** [comment]
@DavidHavl  Can you provide me the full example.

**Comment by DavidHavl** [comment]
@vrkansagara That actually was a full example.
So here is step by step guide:
Find ServiceManager file in your vendor directory (typically: /vendor/zendframework/zend-servicemanager/src/ServiceManager.php  OR /vendor/Zend/ServiceManager/ServiceManager.php )
and change the first 2 lines from:

`

    namespace Zend\ServiceManager;

    class ServiceManager implements ServiceLocatorInterface
    {
`

to:

` 

    namespace Zend\ServiceManager;

    use Psr\Container\ContainerInterface

    class ServiceManager implements ServiceLocatorInterface, ContainerInterface
    {
`

You also need to add the bellow dependency to your composer.json 
`
"container-interop/container-interop": "~1.0"
`

**Comment by DavidHavl** [comment]
@vrkansagara Alternatively you can just replace the content of ServiceLocatorInterface.php in the same folder as the ServiceManager.php with the following content:

`

    <?php
    /**
     * Zend Framework (http://framework.zend.com/)
     *
     * @link      http://github.com/zendframework/zf2 for the canonical source repository
     * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
     * @license   http://framework.zend.com/license/new-bsd New BSD License
     */
    
    namespace Zend\ServiceManager;
    
    use Interop\Container\ContainerInterface;
    
    /**
     * Service locator interface
     */
    interface ServiceLocatorInterface extends ContainerInterface
    {
        /**
         * Retrieve a registered instance
         *
         * @param  string  $name
         * @throws Exception\ServiceNotFoundException
         * @return object|array
         */
        public function get($name);
    
        /**
         * Check for a registered instance
         *
         * @param  string|array  $name
         * @return bool
         */
        public function has($name);
    }

`
Again, you also need to add the bellow dependency to your composer.json
"container-interop/container-interop": "~1.0"


This is exactly how Zend has solved it in versions 2.5 and higher.
